name: Code quality tests

on:
 push:
  branches: ["*"]
 pull_request:
  branches: ["*"]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
   - name: Run ESLint
     uses: stefanoeb/eslint-action@1.0.2

 test:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v3
   - uses: pnpm/action-setup@v2
     with:
      version: 7
   - name: Use Node.js
     uses: actions/setup-node@v3
     with:
      node-version: "18.x"
      cache: "pnpm"
   - run: pnpm install
   - run: pnpm run test
